import { firstValueFrom, toArray } from "rxjs";
import { ObservableFileReaderUtils } from "../../dist";
import { ObservableFileReader } from "../interfaces";
import {
  AbstractObservableFileReader,
  ObservableArrayBufferFromFileReader,
  ObservableDataURLFromFileReader,
  ObservableTextFromFileReader,
} from "./observable-file-reader.class";

describe(`Test of ${AbstractObservableFileReader.name} `, () => {
  const blob = new Blob(["Text file content"], { type: "text/plain" });

  for (const func of Object.values(ObservableFileReaderUtils)) {
    it(`it must return an instance with '${func.name}': `, () =>
      expect(func(blob)).toBeTruthy());
  }

  for (const clazz of [
    ObservableArrayBufferFromFileReader,
    ObservableDataURLFromFileReader,
    ObservableTextFromFileReader,
  ]) {
    it(`it must instantiate with '${clazz.name}'`, () =>
      expect(new clazz(blob)).toBeTruthy());
  }

  for (const func of Object.values(ObservableFileReaderUtils)) {
    describe(`test instance generated by '${func.name}': `, () => {
      let observableFileReader: ObservableFileReader;

      beforeEach(() => (observableFileReader = func(blob)));

      afterEach(() => observableFileReader.result$.subscribe());

      it(`the readyStateList must be: `, async () => {
        firstValueFrom(observableFileReader.readyState$.pipe(toArray())).then(
          (result) => expect(result).toEqual([0, 1, 2])
        );
      });

      it(`the loadStart$ must emit: `, async () => {
        firstValueFrom(observableFileReader.loadStartEvent$).then((event) => {
          expect(event).toBeTruthy();
        });
      });

      it(`the progressEvent$ must emit: `, async () => {
        firstValueFrom(
          observableFileReader.progressEvent$.pipe(toArray())
        ).then((progressEvent) => {
          expect(progressEvent).toBeTruthy();
        });
      });

      it(`the loadEndEvent$ must emit: `, async () => {
        firstValueFrom(observableFileReader.loadEndEvent$).then(
          (progressEvent) => {
            expect(progressEvent).toBeTruthy();
          }
        );
      });

      it(`the loadEvent$ must emit: `, async () => {
        firstValueFrom(observableFileReader.loadEvent$.pipe(toArray())).then(
          (progressEvent) => {
            expect(progressEvent).toBeTruthy();
          }
        );
      });
    });
  }
});
